baseURL = "https://iksic-3325dg.github.io/Nostalgic-Railway-Blog/"
languageCode = "ja"
title = "Nostalgic Railway Blog"

# テーマに依存しない完全静的を優先。PaperModの指定は残っててもOKだが不要。
theme = ""

# 重要: 余計なURL正規化を避ける
canonifyURLs = false