baseURL = "https://iksic-3325dg.github.io/Nostalgic-Railway-Blog/"
languageCode = "ja"
title = "Nostalgic Railway Blog"
theme = "PaperMod"
enableRobotsTXT = true
defaultContentLanguage = "ja"
hasCJKLanguage = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[params]
  env = "production"
  title = "Nostalgic Railway Blog"
  description = "懐かしい鉄道の風景をめぐる旅"
  keywords = ["鉄道", "旅", "ノスタルジー", "写真"]
  author = "あなたの名前"
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true