name: Build and Deploy (Hugo + Pagefind)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Pagefind CLI
        run: npm install -g pagefind

      - name: Build Hugo site
        run: hugo --minify

      - name: Run Pagefind (index into public/pagefind)
        run: pagefind --site "./public" --output-path "./public/pagefind"

      - name: Verify Pagefind output
        run: ls -lah ./public/pagefind || exit 1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true

