name: Build and Deploy (static + Pagefind)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo (static passthrough)
        run: hugo --minify

      - name: Install Pagefind
        run: npm i -g pagefind

      - name: Run Pagefind
        run: pagefind --site "./public" --output-path "./public/pagefind"

      - name: Verify Pagefind output
        run: ls -la ./public/pagefind && grep -m1 pagefind.js ./public/pagefind/pagefind.js && echo "OK"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
