name: Build and Deploy with Pagefind

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # まず Hugo ビルド（static 以下のHTMLも public にコピーされます）
      - name: Build Hugo site
        run: |
          hugo --minify --gc --cleanDestinationDir
          echo "---- public preview ----"
          ls -la ./public | head -n 100

      # Pagefind を入れて index を生成
      - name: Install Pagefind
        run: npm i -g pagefind@latest

      - name: Run Pagefind
        run: |
          pagefind --site "./public" --output-path "./public/pagefind" --force-language ja --verbose
          test -f ./public/pagefind/manifest.json

      # ここでルート一覧を必ず出力（デバッグ用）
      - name: Inspect Pagefind output (routes + count)
        run: |
          echo "---- pagefind dir ----"
          ls -la ./public/pagefind
          echo "---- manifest head ----"
          head -c 400 ./public/pagefind/manifest.json || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
